name: new_test_store
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Updated Firebase versions for better compatibility
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  
  # Firebase UI packages
  firebase_ui_auth: ^1.12.0
  firebase_ui_firestore: ^1.5.17
  
  provider: ^6.1.2
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.5.1
  intl: ^0.20.2
  pdf: ^3.10.6
  printing: ^5.12.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0

  universal_html: ^2.2.4  # For web compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/online-shopping.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter:
  uses-material-design: true
  
  assets:
  - assets/images/
